- name: Configure Backend setUp
  hosts: backend
  become: yes
  tasks:
  - name: Disable node js
    ansible.builtin.dnf:
      name: nodejs
      state: absent
  
  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y
    
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present