- name: SetUp frontend
  hosts: frontend
  become: yes
  tasks:
  - name: install & enable nginx
    ansible.bultin.dnf:
      name: nginx
      state: present
      enabled: yes

  - name: Start nginx
    ansible.builtin.service:
      name: nginx
      state: started

  - name: remove files
    ansible.builtin.command: rm -rf /usr/share/nginx/html/*

  - name: create a file
    ansible.builtin.file:
      path: "/tmp/frontend.zip"
      state: touch
      mode: '777'

  - name: download zip file
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: Unzip files
   ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  - name: copy frondend file
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/systemd/system/expense.conf

  - name: start & enable backend
    ansible.builtin.service:
      name: nginx
      state: restarted

